spring:
  batch:
    jdbc:
      initialize-schema: always
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/example_batch
#    username: root
#    password: password
  jpa:
    hibernate:
      ddl-auto: update
